### ISSUE TITLE
move to specs repo

### ISSUE THREAD

**Issue by dryajov** [libp2p/mplex#4]
Is there any reason this is not under the specs repo? I can move it if no one objects.

// cc @diasdavid @Stebalien

**Comment by daviddias** [comment]
It is the spec of a stream multiplexer, not only libp2p. (same that we don't have SPDY or QUIC inside libp2p specS).

**Comment by ghost** [comment]
I think it's very useful to at least have every related spec *linked* in the spec repo. Otherwise the discoverability suffers from repo-itis.
